# Generated by Django 2.2.16 on 2020-10-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLavados', '0003_insumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionyVision',
            fields=[
                ('ident', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
